"""
Example demonstrating performance analysis and regime-specific metrics.

This example shows how to:
1. Calculate comprehensive performance metrics
2. Analyze performance by market regime
3. Perform signal attribution analysis
4. Compare to benchmark
5. Generate performance reports
"""

import sys
from pathlib import Path
from datetime import datetime, timedelta
import numpy as np
import pandas as pd

# Add parent directory to path for imports
sys.path.insert(0, str(Path(__file__).parent.parent))

from imp.backtesting import (
    PerformanceAnalyzer,
    RegimePerformanceAnalyzer,
    PerformanceConfig,
    PortfolioState,
    Order,
    TradeSignal,
    TradeAction,
    ProcessedSignal,
    SignalDirection,
)


def create_sample_data():
    """Create sample portfolio snapshots and orders for demonstration."""
    print("Creating sample data...")
    
    # Initialize portfolio
    initial_capital = 100000.0
    start_time = datetime(2024, 1, 1)
    portfolio = PortfolioState(initial_capital, start_time)
    
    # Simulate trading over 100 periods
    snapshots = []
    orders = []
    
    current_time = start_time
    current_price = 50000.0
    position = 0.0
    
    # Create regime data (3 regimes cycling)
    regime_states = []
    
    for i in range(100):
        current_time += timedelta(minutes=5)
        
        # Simulate price movement
        price_change = np.random.normal(0, 0.01)
        current_price *= (1 + price_change)
        
        # Determine regime (cycle through 3 regimes)
        regime_state = i % 3
        regime_states.append({'timestamp': current_time, 'regime_state': regime_state})
        
        # Generate trading signals based on regime
        if i % 10 == 0:  # Trade every 10 periods
            # Determine signal source based on regime
            if regime_state == 0:
                signal_source = 'ldc'
            elif regime_state == 1:
                signal_source = 'mr'
            else:
                signal_source = 'tsmom'
            
            # Create trade signal
            if position == 0:
                # Open position
                action = TradeAction.BUY
                side = 'buy'
                quantity = 1.0
            else:
                # Close position
                action = TradeAction.CLOSE_LONG
                side = 'sell'
                quantity = abs(position)
            
            # Create processed signal
            processed_signal = ProcessedSignal(
                timestamp=current_time,
                symbol='BTCUSDT',
                direction=SignalDirection.BUY if action == TradeAction.BUY else SignalDirection.SELL,
                strength=0.65,
                signal_source=signal_source,
                raw_signals={'ldc': 0.7, 'mr': 0.5, 'tsmom': 0.6, 'fusion': 0.65},
                regime_state=regime_state,
                regime_weights={'ldc': 0.4, 'mr': 0.3, 'tsmom': 0.3},
                metadata={}
            )
            
            # Create trade signal
            trade_signal = TradeSignal(
                trade_id=f"trade_{i}",
                timestamp=current_time,
                symbol='BTCUSDT',
                action=action,
                confidence=0.65,
                signal_source=signal_source,
                reasoning=f"Generated by {signal_source} in regime {regime_state}",
                processed_signal=processed_signal,
                metadata={}
            )
            
            # Create order
            order = Order(
                order_id=f"order_{i}",
                timestamp=current_time,
                symbol='BTCUSDT',
                side=side,
                quantity=quantity,
                price=current_price,
                order_type='market',
                trade_signal=trade_signal,
                position_size_method='percentage',
                risk_checks_passed={'all': True},
                metadata={
                    'signal_source': signal_source,
                    'regime_state': regime_state
                }
            )
            
            orders.append(order)
            
            # Update portfolio
            portfolio.update_from_order(order, current_price, commission=10.0, slippage=5.0)
            
            if side == 'buy':
                position = quantity
            else:
                position = 0.0
        
        # Update prices
        portfolio.update_prices({'BTCUSDT': current_price}, current_time)
        
        # Take snapshot
        snapshot = portfolio.take_snapshot(current_time)
        snapshots.append(snapshot)
    
    # Create regime DataFrame
    regime_df = pd.DataFrame(regime_states)
    
    print(f"Created {len(snapshots)} snapshots and {len(orders)} orders")
    print(f"Final portfolio value: ${portfolio.total_value:,.2f}")
    print(f"Total P&L: ${portfolio.total_pnl:,.2f} ({portfolio.return_pct:.2f}%)")
    
    return snapshots, orders, initial_capital, regime_df


def demonstrate_performance_analysis():
    """Demonstrate basic performance analysis."""
    print("\n" + "="*80)
    print("BASIC PERFORMANCE ANALYSIS")
    print("="*80)
    
    # Create sample data
    snapshots, orders, initial_capital, regime_df = create_sample_data()
    
    # Initialize performance analyzer
    config = PerformanceConfig(
        risk_free_rate=0.02,
        var_confidence=0.95,
        regime_analysis=True,
        attribution_analysis=True
    )
    
    analyzer = PerformanceAnalyzer(config)
    
    # Calculate metrics
    print("\nCalculating performance metrics...")
    metrics = analyzer.calculate_metrics(snapshots, orders, initial_capital)
    
    # Display results
    print("\n--- Performance Metrics ---")
    print(f"Total Return: {metrics.total_return:.2%}")
    print(f"Annualized Return: {metrics.annualized_return:.2%}")
    print(f"Volatility: {metrics.annualized_volatility:.2%}")
    print(f"Sharpe Ratio: {metrics.sharpe_ratio:.2f}")
    print(f"Sortino Ratio: {metrics.sortino_ratio:.2f}")
    print(f"Calmar Ratio: {metrics.calmar_ratio:.2f}")
    print(f"Max Drawdown: {metrics.max_drawdown:.2%}")
    print(f"Max Drawdown Duration: {metrics.max_drawdown_duration} periods")
    print(f"VaR (95%): {metrics.var_95:.2%}")
    print(f"CVaR (95%): {metrics.cvar_95:.2%}")
    
    print("\n--- Trade Statistics ---")
    print(f"Number of Trades: {metrics.num_trades}")
    print(f"Win Rate: {metrics.win_rate:.1%}")
    print(f"Profit Factor: {metrics.profit_factor:.2f}")
    print(f"Average Win: ${metrics.avg_win:.2f}")
    print(f"Average Loss: ${metrics.avg_loss:.2f}")


def demonstrate_regime_analysis():
    """Demonstrate regime-specific performance analysis."""
    print("\n" + "="*80)
    print("REGIME-SPECIFIC PERFORMANCE ANALYSIS")
    print("="*80)
    
    # Create sample data
    snapshots, orders, initial_capital, regime_df = create_sample_data()
    
    # Initialize regime performance analyzer
    config = PerformanceConfig(
        risk_free_rate=0.02,
        regime_analysis=True
    )
    
    regime_names = {
        0: "Bull Market",
        1: "Bear Market",
        2: "Sideways Market"
    }
    
    analyzer = RegimePerformanceAnalyzer(config, regime_names)
    
    # Analyze by regime
    print("\nAnalyzing performance by regime...")
    regime_metrics = analyzer.analyze_by_regime(
        snapshots, orders, initial_capital, regime_df
    )
    
    # Display results
    print("\n--- Performance by Regime ---")
    for state, metrics in sorted(regime_metrics.items()):
        print(f"\n{metrics.regime_name} (State {state}):")
        print(f"  Time in Regime: {metrics.time_pct:.1%}")
        print(f"  Total Return: {metrics.total_return:.2%}")
        print(f"  Annualized Return: {metrics.annualized_return:.2%}")
        print(f"  Sharpe Ratio: {metrics.sharpe_ratio:.2f}")
        print(f"  Number of Trades: {metrics.num_trades}")
        print(f"  Win Rate: {metrics.win_rate:.1%}")
        print(f"  Contribution to Return: {metrics.contribution_to_return:.2%}")


def demonstrate_signal_attribution():
    """Demonstrate signal attribution analysis."""
    print("\n" + "="*80)
    print("SIGNAL ATTRIBUTION ANALYSIS")
    print("="*80)
    
    # Create sample data
    snapshots, orders, initial_capital, regime_df = create_sample_data()
    
    # Initialize regime performance analyzer
    config = PerformanceConfig(
        attribution_analysis=True
    )
    
    analyzer = RegimePerformanceAnalyzer(config)
    
    # Analyze signal attribution
    print("\nAnalyzing performance attribution by signal source...")
    attributions = analyzer.analyze_signal_attribution(
        orders, snapshots, initial_capital
    )
    
    # Display results
    print("\n--- Performance Attribution by Signal ---")
    for source, attr in sorted(attributions.items()):
        print(f"\n{source.upper()}:")
        print(f"  Number of Trades: {attr.num_trades} ({attr.trade_pct:.1%} of total)")
        print(f"  Total P&L: ${attr.total_pnl:.2f}")
        print(f"  Average P&L: ${attr.avg_pnl:.2f}")
        print(f"  Win Rate: {attr.win_rate:.1%}")
        print(f"  Contribution to Return: {attr.contribution_to_return:.2%}")
        print(f"  Contribution %: {attr.contribution_pct:.1%}")


def demonstrate_benchmark_comparison():
    """Demonstrate benchmark comparison."""
    print("\n" + "="*80)
    print("BENCHMARK COMPARISON")
    print("="*80)
    
    # Create sample data
    snapshots, orders, initial_capital, regime_df = create_sample_data()
    
    # Create synthetic benchmark data (buy-and-hold)
    print("\nCreating benchmark data (buy-and-hold)...")
    benchmark_data = []
    start_price = 50000.0
    current_price = start_price
    
    for snapshot in snapshots:
        # Simulate benchmark price movement
        price_change = np.random.normal(0.0001, 0.008)  # Slightly positive drift
        current_price *= (1 + price_change)
        
        benchmark_data.append({
            'timestamp': snapshot.timestamp,
            'close': current_price
        })
    
    benchmark_df = pd.DataFrame(benchmark_data)
    
    # Initialize performance analyzer
    config = PerformanceConfig(
        benchmark_symbol='BTCUSDT',
        risk_free_rate=0.02
    )
    
    analyzer = PerformanceAnalyzer(config)
    
    # Compare to benchmark
    print("\nComparing to benchmark...")
    comparison = analyzer.compare_to_benchmark(
        snapshots, benchmark_df, initial_capital
    )
    
    # Display results
    print("\n--- Benchmark Comparison ---")
    print(f"Strategy Return: {comparison.strategy_return:.2%}")
    print(f"Benchmark Return: {comparison.benchmark_return:.2%}")
    print(f"Excess Return: {comparison.excess_return:.2%}")
    print(f"Alpha: {comparison.alpha:.4f}")
    print(f"Beta: {comparison.beta:.2f}")
    print(f"Information Ratio: {comparison.information_ratio:.2f}")
    print(f"Tracking Error: {comparison.tracking_error:.4f}")
    print(f"Correlation: {comparison.correlation:.2f}")


def demonstrate_time_series_performance():
    """Demonstrate time-series performance tracking."""
    print("\n" + "="*80)
    print("TIME-SERIES PERFORMANCE TRACKING")
    print("="*80)
    
    # Create sample data
    snapshots, orders, initial_capital, regime_df = create_sample_data()
    
    # Initialize regime performance analyzer
    config = PerformanceConfig()
    analyzer = RegimePerformanceAnalyzer(config)
    
    # Create time-series performance
    print("\nCreating time-series performance data...")
    ts_performance = analyzer.create_time_series_performance(
        snapshots, regime_df, initial_capital
    )
    
    # Convert to DataFrame for display
    df = ts_performance.to_dataframe()
    
    print(f"\nTime-series data shape: {df.shape}")
    print("\nFirst 5 rows:")
    print(df.head())
    
    print("\nLast 5 rows:")
    print(df.tail())
    
    print("\nSummary statistics:")
    print(df[['equity_value', 'returns', 'cumulative_returns', 'drawdowns']].describe())


def demonstrate_comprehensive_report():
    """Demonstrate comprehensive regime report generation."""
    print("\n" + "="*80)
    print("COMPREHENSIVE REGIME REPORT")
    print("="*80)
    
    # Create sample data
    snapshots, orders, initial_capital, regime_df = create_sample_data()
    
    # Initialize analyzers
    config = PerformanceConfig(
        risk_free_rate=0.02,
        regime_analysis=True,
        attribution_analysis=True
    )
    
    base_analyzer = PerformanceAnalyzer(config)
    regime_analyzer = RegimePerformanceAnalyzer(
        config,
        regime_names={0: "Bull", 1: "Bear", 2: "Sideways"}
    )
    
    # Calculate all metrics
    print("\nCalculating comprehensive metrics...")
    overall_metrics = base_analyzer.calculate_metrics(snapshots, orders, initial_capital)
    regime_metrics = regime_analyzer.analyze_by_regime(
        snapshots, orders, initial_capital, regime_df
    )
    signal_attributions = regime_analyzer.analyze_signal_attribution(
        orders, snapshots, initial_capital
    )
    
    # Generate report
    print("\nGenerating comprehensive report...")
    report = regime_analyzer.generate_regime_report(
        regime_metrics, signal_attributions, overall_metrics
    )
    
    # Display report summary
    print("\n--- Overall Performance ---")
    print(f"Total Return: {report['overall_performance']['total_return']:.2%}")
    print(f"Sharpe Ratio: {report['overall_performance']['sharpe_ratio']:.2f}")
    print(f"Max Drawdown: {report['overall_performance']['max_drawdown']:.2%}")
    
    print("\n--- Regime Analysis Summary ---")
    regime_summary = report['regime_analysis']['summary']
    print(f"Number of Regimes: {regime_summary['num_regimes']}")
    print(f"Best Regime: {regime_summary['best_regime']['name']} "
          f"({regime_summary['best_regime']['return']:.2%})")
    print(f"Worst Regime: {regime_summary['worst_regime']['name']} "
          f"({regime_summary['worst_regime']['return']:.2%})")
    
    print("\n--- Signal Attribution Summary ---")
    signal_summary = report['signal_attribution']['summary']
    print(f"Number of Signals: {signal_summary['num_signals']}")
    print(f"Best Signal: {signal_summary['best_signal']['source']} "
          f"(${signal_summary['best_signal']['pnl']:.2f})")
    print(f"Total Trades: {signal_summary['total_trades']}")
    print(f"Total P&L: ${signal_summary['total_pnl']:.2f}")


def main():
    """Run all demonstrations."""
    print("="*80)
    print("PERFORMANCE ANALYSIS EXAMPLES")
    print("="*80)
    
    try:
        # Run demonstrations
        demonstrate_performance_analysis()
        demonstrate_regime_analysis()
        demonstrate_signal_attribution()
        demonstrate_benchmark_comparison()
        demonstrate_time_series_performance()
        demonstrate_comprehensive_report()
        
        print("\n" + "="*80)
        print("ALL EXAMPLES COMPLETED SUCCESSFULLY")
        print("="*80)
        
    except Exception as e:
        print(f"\nError running examples: {e}")
        import traceback
        traceback.print_exc()
        return 1
    
    return 0


if __name__ == "__main__":
    sys.exit(main())
